Fix copyright year 2021
sugarchain-project/sugarchain pull request #191
Opened 2021-02-09 19:19 UTC by lrhel

fixes #187

2021-02-14 21:28 UTC, decryp2kanon requested changes
this man help should be automatically generated. no need to edit here

2021-02-14 21:28 UTC, decryp2kanon commented on doc/man/sugarchain-cli.1
> +Copyright (C) 2018-2021 The Sugarchain Yumekawa developers
this man help should be automatically generated. no need to edit here

2021-02-14 21:28 UTC, decryp2kanon commented on doc/man/sugarchain-qt.1
> +Copyright (C) 2018-2021 The Sugarchain Yumekawa developers
this man help should be automatically generated. no need to edit here

2021-02-14 21:28 UTC, decryp2kanon commented on doc/man/sugarchain-tx.1
> +Copyright (C) 2018-2021 The Sugarchain Yumekawa developers
this man help should be automatically generated. no need to edit here

2021-02-14 21:28 UTC, decryp2kanon commented on doc/man/sugarchaind.1
> +Copyright (C) 2018-2021 The Sugarchain Yumekawa developers
this man help should be automatically generated. no need to edit here

2021-02-27 08:30 UTC, lrhel commented
my bad, uncommitted the man pages

2023-02-08 13:36 UTC, decryp2kanon commented
closing due to too old

2023-02-08 13:36 UTC, closed without merging