Added work caching
sugarchain-project/sugarchain pull request #22
Opened 2019-12-05 04:02 UTC by volbil

Originary implemented by https://github.com/ResistancePlatform/resistance-core/commit/a73d69465c8884e6289ecbdec58331e8fdc0376a

2019-12-05 04:21 UTC, cryptozeny commented
AWESOME i will check it soon as possible.

2019-12-05 12:51 UTC, cryptozeny commented
no error found on `make check`
```
PASS: exhaustive_tests
PASS: qt/test/test_sugarchain-qt
PASS: tests
============================================================================
Testsuite summary for libsecp256k1 0.1
============================================================================
# TOTAL: 2
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[6]: Leaving directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/src/secp256k1'
make[5]: Leaving directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/src/secp256k1'
make[4]: Leaving directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/src/secp256k1'
make[4]: Entering directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/src/univalue'
  CXX      lib/libunivalue_la-univalue_get.lo
  CXXLD    libunivalue.la
  CXXLD    test/no_nul
  CXXLD    test/test_json
  CXXLD    test/unitester
make  check-TESTS
make[5]: Entering directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/src/univalue'
make[6]: Entering directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/src/univalue'
PASS: test/no_nul
PASS: test/object
PASS: test/unitester
============================================================================
Testsuite summary for univalue 1.0.3
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[6]: Leaving directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/src/univalue'
make[5]: Leaving directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/src/univalue'
make[4]: Leaving directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/src/univalue'
PASS: test/test_sugarchain
============================================================================
Testsuite summary for Sugarchain Yumekawa 0.16.3
============================================================================
# TOTAL: 2
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[4]: Leaving directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/src'
make[3]: Leaving directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/src'
make[2]: Leaving directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/src'
make[1]: Leaving directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/src'
Making check in doc/man
make[1]: Entering directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/doc/man'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain/doc/man'
make[1]: Entering directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain'
make[1]: Nothing to be done for 'check-am'.
make[1]: Leaving directory '/home/ak/git/SUGAR/SUGARCHAIN/sugarchain'
```

2019-12-05 13:16 UTC, cryptozeny commented
```
./src/test/test_sugarchain test_bitcoin --log_level=test_suite
Running 282 test cases...

*** No errors detected
```

2019-12-05 13:17 UTC, cryptozeny commented
Still testing...

2019-12-06 06:47 UTC, volbil commented
Backported address index from this commits:
https://github.com/MicroBitcoinOrg/MicroBitcoin/commit/34ef71b734d4995592ad3a4c176bf2a81257e217
https://github.com/MicroBitcoinOrg/MicroBitcoin/commit/2ec3a1b5efe23a9848c2a7ad46b6258e6eed88b4

2019-12-07 16:26 UTC, cryptozeny commented
**DO NOT MERGE YET**

2019-12-09 02:54 UTC, cryptozeny commented
https://github.com/sugarchain-project/sugarchain/pull/26
benchmark

2019-12-21 17:11 UTC, cryptozeny commented on src/primitives/block.cpp
> +        printf("HIT block_hash = %s PoW_hash = %s\n", cache_block_hash.ToString().c_str(), cache_PoW_hash.ToString().c_str());
check log vs RES

2019-12-21 17:11 UTC, cryptozeny commented on src/primitives/block.cpp
> +        printf("MISS block_hash = %s PoW_hash = %s\n", cache_block_hash.ToString().c_str(), cache_PoW_hash.ToString().c_str());
check log vs RES, and if its OK, comment this out.

2019-12-21 18:02 UTC, cryptozeny commented
8e5b110 no error on tests

2019-12-21 18:56 UTC, cryptozeny commented
sync logging
https://youtu.be/MojeGzy2NHU

IBD 3x faster
![image](https://user-images.githubusercontent.com/37016180/71312484-e0847100-246e-11ea-9d64-aff3a4c23acb.png)

reindex 2.4x faster
![image](https://user-images.githubusercontent.com/37016180/71312493-ec703300-246e-11ea-9a51-4aa7d6270361.png)

2019-12-22 15:20 UTC, cryptozeny commented
log
```
O block = 8966e8eed0ac54c65546d0f3c369b0eaed6558afd80cfd4e45e22f5c322413c1 PoW = 0000071bc4bc6a2b1f8721b8ffd2f14ac688ba2d68cb52e1bedbb95cc64c8633
X block = cba1cfff0fd1bc43ba5508f3113502d1f77c803afd9ca295e1ad2303ba80397e PoW = 000004e5ef92746b970adde07576e89f8f73434efc67cb7704fd0021bdcb5265
O block = cba1cfff0fd1bc43ba5508f3113502d1f77c803afd9ca295e1ad2303ba80397e PoW = 000004e5ef92746b970adde07576e89f8f73434efc67cb7704fd0021bdcb5265
X block = a3f0556b4db92179d5bf961f9c16406886a669b522caf43a18d6ad48b0b7490d PoW = 00000167626529c9ce87bb85e40f8f992359fb31ebdc9af49dbf1cb7ef2db6a1
O block = a3f0556b4db92179d5bf961f9c16406886a669b522caf43a18d6ad48b0b7490d PoW = 00000167626529c9ce87bb85e40f8f992359fb31ebdc9af49dbf1cb7ef2db6a1
X block = ed8461b33a2534f537d7a07e95c6dd9fa7f9915c3761ebd16f4cebc562e8b14c PoW = 000006b5c8d01e40596a914d0235d79bc9d4402e4c6665353440bc02b60697aa
O block = ed8461b33a2534f537d7a07e95c6dd9fa7f9915c3761ebd16f4cebc562e8b14c PoW = 000006b5c8d01e40596a914d0235d79bc9d4402e4c6665353440bc02b60697aa
X block = b32e64b7f26282eb2bf4990e4f03b83b6644ad71af3919aa89c5f87687f463c8 PoW = 0000004271c1f17d3f4c96bad6d69360b19bde4a9fdeacae01767768f7591ec9
O block = b32e64b7f26282eb2bf4990e4f03b83b6644ad71af3919aa89c5f87687f463c8 PoW = 0000004271c1f17d3f4c96bad6d69360b19bde4a9fdeacae01767768f7591ec9
X block = 031bc4827cec6b1b56292e870278b4d103150c51634f22d954fced9ec78dd153 PoW = 0000079b8815fe58bc73c99d60240b69e4aefa8623c4314599efbfb7af02aaa5
O block = 031bc4827cec6b1b56292e870278b4d103150c51634f22d954fced9ec78dd153 PoW = 0000079b8815fe58bc73c99d60240b69e4aefa8623c4314599efbfb7af02aaa5
X block = c7d37106b96c8e9e11d57a3b06ace1a3535cac972b7672602f98e1befad5db08 PoW = 000006323eab4101ef2445c6b8fdb713e11f9cfbb0be8d9a35fd1a878eeaf9b1
O block = c7d37106b96c8e9e11d57a3b06ace1a3535cac972b7672602f98e1befad5db08 PoW = 000006323eab4101ef2445c6b8fdb713e11f9cfbb0be8d9a35fd1a878eeaf9b1
X block = 34960049b2238e9ea079726ea713b21891984effedd5fc3be8e11bf55f7f8d88 PoW = 000002f51a41a53258bfc5a8b2659cc69da4ee931ecec7e4717833d09930c1e3
O block = 34960049b2238e9ea079726ea713b21891984effedd5fc3be8e11bf55f7f8d88 PoW = 000002f51a41a53258bfc5a8b2659cc69da4ee931ecec7e4717833d09930c1e3
X block = 2208b3e7de6591904c3a658d378f8a2713287919b736e9a0d1a1ed007dab76ee PoW = 00000430a393799e7db231169536868cf3a9146716039374c1e738a8b2e875fa
O block = 2208b3e7de6591904c3a658d378f8a2713287919b736e9a0d1a1ed007dab76ee PoW = 00000430a393799e7db231169536868cf3a9146716039374c1e738a8b2e875fa
X block = 8060d16d884d5631b012ff95507838b973a6c8be80b99ee3854d81a3867e666d PoW = 000006f24bc50a78842bd7c65691520ac2e263c64c3c799d1d81246d8b4707a7
O block = 8060d16d884d5631b012ff95507838b973a6c8be80b99ee3854d81a3867e666d PoW = 000006f24bc50a78842bd7c65691520ac2e263c64c3c799d1d81246d8b4707a7
X block = fab57cbb173d49f17e24b9672aa854300300cd8d3939d5562db66ba3f9aea19b PoW = 00000476e2a983b0ba617d5c290c469638760f676248c65ffeb7d8714213b31f
O block = fab57cbb173d49f17e24b9672aa854300300cd8d3939d5562db66ba3f9aea19b PoW = 00000476e2a983b0ba617d5c290c469638760f676248c65ffeb7d8714213b31f
X block = 3a8f9c58dcfd397fede17e9dc7fd23c0667b26a847ca3bbccddf6d567358fa7c PoW = 0000085dc5a994da2d4cc161ad4110d720043c553665bee67a25166a2cbfe134
O block = 3a8f9c58dcfd397fede17e9dc7fd23c0667b26a847ca3bbccddf6d567358fa7c PoW = 0000085dc5a994da2d4cc161ad4110d720043c553665bee67a25166a2cbfe134
X block = 1dc70f8396c9dc03a8f221c9899b1430c36f9db94a785db57e7db60371a0ca42 PoW = 000005d66ee7cb04872d98f99395351fd3d8e599e21ad0e33325f4b1f9816bdd
```

2019-12-22 15:59 UTC, cryptozeny commented
check
https://github.com/ResistancePlatform/resistance-core/compare/20c7ba33101133053bd001a84479ff341a134cba...3c80dac3618e42c90057da7ba6fa49c44cf64349

2019-12-22 16:10 UTC, cryptozeny commented
RES
![image](https://user-images.githubusercontent.com/37016180/71324327-ed619d00-2520-11ea-818e-19ac82780e0d.png)

SUGAR
![image](https://user-images.githubusercontent.com/37016180/71324333-fbafb900-2520-11ea-9979-c65ac2ee117d.png)

BTC
![image](https://user-images.githubusercontent.com/37016180/71324337-0cf8c580-2521-11ea-893d-2115bea72bcf.png)

OK

2019-12-22 16:12 UTC, cryptozeny approved these changes
Tested ACK 8e5b110

2019-12-22 16:13 UTC, cryptozeny commented
TODO: remove `printf` in `block.cpp`

2019-12-22 20:45 UTC, cryptozeny approved these changes
Tested ACK 8e5b110

2019-12-22 20:50 UTC, solardiz commented
Also relevant is https://github.com/ResistancePlatform/resistance-core/commit/4efff3000711cc414e76cd57f2e605762b6cc339 which sets MAX_BLOCKS_IN_TRANSIT_PER_PEER to be same as MAX_HEADERS_RESULTS. Without this change, at least in Resistance the block headers download would get unnecessarily far ahead of the full blocks download, resulting in more work lost and redone in case the initial blocks download is interrupted and continued. The work loss is because we do not yet store cached PoWs on disk.

2019-12-22 21:58 UTC, cryptozeny commented
thanks to advice to us! @solardiz :smile: 

after you, i changed both. SUGAR blocktime is 5 seconds so 120x faster than BTC.
```cpp
static const int MAX_BLOCKS_IN_TRANSIT_PER_PEER = 1920; // BTC was 16 // 16*120=1920
static const unsigned int MAX_HEADERS_RESULTS = 1920; // BTC was 2000
```

but i got this error, and all banned from other nodes...
```
ERROR: headers message size = 2000
Misbehaving: 157.245.69.15:34230 peer=0 (80 -> 100) BAN THRESHOLD EXCEEDED
```
![image](https://user-images.githubusercontent.com/37016180/71327882-785a8b80-2551-11ea-915c-20d1b91850df.png)

how to fix this? :thinking:

2019-12-22 22:10 UTC, solardiz commented
@cryptozeny Don't change MAX_HEADERS_RESULTS. Just set MAX_BLOCKS_IN_TRANSIT_PER_PEER to some value from e.g. 200 to 2000 - experiment with this.

2019-12-23 01:54 UTC, cryptozeny commented
RESULT:
IBD download only: `3:40`

TODO:
`BLOCK_DOWNLOAD_WINDOW = 1024;` upto `2048` larger than MAX_BLOCKS_IN_TRANSIT_PER_PEER and MAX_HEADERS_RESULTS (2000)

![image](https://user-images.githubusercontent.com/37016180/71330792-47d71980-2572-11ea-8fe5-d9e6686965d6.png)

2019-12-23 13:52 UTC, cryptozeny requested changes
those two parameters should be changed. try some experiment.
```
MAX_BLOCKS_IN_TRANSIT_PER_PEER (16)
BLOCK_DOWNLOAD_WINDOW (1024)
```

but never change `MAX_HEADERS_RESULTS` it causes [unexpected HF](https://github.com/sugarchain-project/sugarchain/pull/22#issuecomment-568306229).

> solardiz commented
Also relevant is ResistancePlatform/resistance-core@4efff30 which sets MAX_BLOCKS_IN_TRANSIT_PER_PEER to be same as MAX_HEADERS_RESULTS. Without this change, at least in Resistance the block headers download would get unnecessarily far ahead of the full blocks download, resulting in more work lost and redone in case the initial blocks download is interrupted and continued. The work loss is because we do not yet store cached PoWs on disk.

> Don't change MAX_HEADERS_RESULTS. Just set MAX_BLOCKS_IN_TRANSIT_PER_PEER to some value from e.g. 200 to 2000 - experiment with this.

2019-12-23 14:40 UTC, cryptozeny commented
bd2d2bb NACK
peer all lost during IBD. at first is OK (8), but later it had `0 peers`, however somehow it find another one. it works anyhow but unacceptable.

2019-12-23 15:33 UTC, solardiz commented
I suggest you keep the parameter changes separate from this PoW caching PR.

2019-12-24 17:14 UTC, cryptozeny approved these changes
Tested ACK f3d91060fc0b1c74b202a97c80ce5fe73c8c17e0

### IBD_4: (revert to ogirinal)
total `7:10`
```
MAX_BLOCKS_IN_TRANSIT_PER_PEER = 16;
BLOCK_DOWNLOAD_WINDOW = 1024;
```
![image](https://user-images.githubusercontent.com/37016180/71420133-dd7bc180-26b6-11ea-9c09-e011a37cdb46.png)

TODO:
> I suggest you keep the parameter changes separate from this PoW caching PR.
- optimize IBD & download
- remove printf

2019-12-24 17:49 UTC, merged

2019-12-24 19:06 UTC, cryptozeny commented
https://github.com/sugarchain-project/sugarchain/issues/23